version: 2
jobs:
  test_android:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/openchs-client

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-android/package.json" }}
          - v1-dependencies-

      - run: sudo apt-get install make

      - run: make deps

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
           - packages/openchs-android/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-android/package.json" }}

      - run: make test-android



  test_health_modules:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/openchs-client

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-health-modules/package.json" }}
          - v1-dependencies-

      - run: sudo apt-get install make

      - run: make deps

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
           - packages/openchs-health-modules/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-health-modules/package.json" }}

      - run: make test-health-modules



  test_models:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/openchs-client

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-models/package.json" }}
          - v1-dependencies-

      - run: sudo apt-get install make

      - run: make deps

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
           - packages/openchs-models/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-models/package.json" }}

      - run: make test-models

  release_android:
    docker:
      - image: openchs/react-native:latest
        environment:
          - TERM: dumb
          - GRADLE_OPTS: "-Xmx250m -Xms250m"


    working_directory: ~/openchs-client

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/openchs-android/android/app/build.gradle" }}
          - v1-dependencies-{{ checksum "packages/openchs-android/package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-health-modules/package.json" }}
          - v1-dependencies-{{ checksum "packages/openchs-models/package.json" }}
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: sudo chmod a+x packages/openchs-android/android/gradlew

      - run: make deps;

      - save_cache:
          paths:
            - packages/openchs-health-modules/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-health-modules/package.json" }}

      - save_cache:
          paths:
            - packages/openchs-models/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-models/package.json" }}

      - save_cache:
          paths:
           - packages/openchs-android/node_modules
          key: v1-dependencies-{{ checksum "packages/openchs-android/package.json" }}

      - save_cache:
          paths:
           - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
           - ~/.m2
           - ~/.gradle
           - ~/openchs-client/packages/openchs-android/android/app/.gradle
           - ~/openchs-client/packages/openchs-android/android/.gradle
          key: v1-dependencies-{{ checksum "packages/openchs-android/android/app/build.gradle" }}

      - run: make release

workflows:
  version: 2
  test_all:
    jobs:
      - release_android

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/0fdffde721194986f2a0