---
- name: Install android-sdk
  homebrew: name=android-sdk state=latest
  tags:
    - android
    - brew

- name: Install Android-SDK tools and versions
  script: install-android-sdk.sh {{item}}
  with_items: '{{android_deps}}'
