---
- name: Update Brew
  homebrew: update_homebrew=yes
  tags:
    - dev
    - brew

- name: Install/Update Flow and Watchman
  homebrew: name={{item}} state=latest
  with_items:
    - flow
    - watchman
  tags:
    - brew
    - dev

- name: Install/Update Node and NPM
  homebrew: name=node state=latest
